# Generated by Django 3.0 on 2020-09-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=350, null=True)),
                ('role', models.CharField(max_length=40)),
                ('img_url', models.CharField(max_length=100)),
                ('linkedin_url', models.CharField(max_length=100)),
                ('mail_id', models.CharField(max_length=100)),
                ('work_desc', models.CharField(max_length=1050, null=True)),
            ],
            options={
                'verbose_name': 'employee_details',
                'verbose_name_plural': 'employee_details',
                'db_table': 'employee_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=305, null=True)),
                ('role', models.CharField(max_length=40)),
                ('img_url', models.CharField(max_length=100)),
                ('linkedin_url', models.CharField(max_length=100)),
                ('mail_id', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('project_desc', models.CharField(max_length=305, null=True)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'db_table': 'project',
                'managed': False,
            },
        ),
    ]
